CREATE USER dnduser
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dndUser;

CREATE USER dndapiuser WITH password 'cjR4Metye4';
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dndapiuser;
